export const GET_COMPANY_DATA_INIT = 'App/GET_COMPANY_DATA_INIT';
export const GET_COMPANY_DATA_SUCCESS = 'App/GET_COMPANY_DATA_SUCCESS';
export const GET_COMPANY_DATA_ERROR = 'App/GET_COMPANY_DATA_ERROR';
